main: com.example.plugin.RTP
version: 1.0
name: RTP
author: IHW0
api-version: 1.21
commands:
  rtp:
    description: Основная команда RTP
    aliases: [randomtp]
permissions:
  rtp.use:
    description: Право на использование /rtp
    default: true
  rtp.admin:
    description: Право на перезагрузку конфига /rtp reload
    default: op